name: Updating a GitHub key - REPOB_V1_TOKEN0

on:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  job0_update_REPOB_V1_TOKEN0:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get repository files - probably do not need it
        uses: actions/checkout@v2
        
      - name: Assign a new value to the secret
        uses: actions/github-script@v6
        env:
          REPOB_V1_TOKEN0: '${{ secrets.REPOB_V1_TOKEN0 }}'
        with:
          result-encoding: string
          github-token: ${{ secrets.REPOB_V1_TOKEN0 || secrets.REPOB_V1_TOKEN1 }}
          script: |

            // --------------------------------
            
            // Get id information about Github Actions Secret
            const publicKey_str = await github.rest.actions.getRepoPublicKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // --------------------------------
            
            // Re-assign the new_secret_value to Github Actions Secret
            await github.rest.actions.createOrUpdateRepoSecret({
                owner: context.repo.owner,
                repo: context.repo.repo,
                secret_name: 'REPOB_V1_TOKEN0',
                encrypted_value: btoa(publicKey_str),
                key_id: publicKey_str.data.key_id,
              });
