name: REPOB processes REPOA data

on:
  push:
    branches:
      - main
    paths:
      - 'webappb/**.txt'
    
jobs:
  dispatch:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Get repository files (equivalent to git pull)
        uses: actions/checkout@v2


      - name: Decrypt the file
        uses: actions/github-script@v4
        env:
          USERNAME: '${username}'
          PUBLIC_KEY_RSA: '${{ secrets.PUBLIC_KEY_RSA }}'
          PRIVATE_KEY_RSA: '${{ secrets.PRIVATE_KEY_RSA }}'
        with:
          github-token: ${{ secrets.REPOB_V1 }}
          script: |

            // Get username from cb.txt


            // Get encrypted data from main_file.csv


            // Decrypt data from main_file.csv

            // --------------------------------

            // Add username to main_file.csv

            // --------------------------------

            // Encrypt data 

            
            // --------------------------------

            // Save encrypted data back to main_file.csv
            const fs = require('fs');
            fs.writeFileSync('webappb/main_file.csv', encrypted_data);


      - name: Commit and push changes back to repository
        run:  git config --global user.email "j622amilah@gmail.com"; git config --global user.name "CodeSolutions2"; git pull origin main; git checkout main; git branch --set-upstream-to origin/main; git merge main --ff-only; git add -A; git diff-index --quiet HEAD || git commit -m "add files" --allow-empty; git push https://${{ secrets.REPOB_V1 }}@github.com/CodeSolutions2/frontend_backend_message_passing_central_repository_v1.git
